name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "Language: EN"]
body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: 'A bug...'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **To Reproduce**
        Steps to reproduce the behavior:
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Expected behavior**
        A clear and concise description of what you expected to happen.
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What you expected to happen.
      placeholder: 'I expected...'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Screenshots**
        If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: 'Upload images or drag & drop.'
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Desktop (please complete the following information):**
         - OS: [e.g. Linux]
         - Version [e.g. any]
  - type: input
    id: desktop-os
    attributes:
      label: Desktop OS
      description: The operating system you're using.
      placeholder: e.g. Linux
    validations:
      required: true

  - type: input
    id: desktop-version
    attributes:
      label: Desktop Version
      description: The version of the OS.
      placeholder: e.g. any
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Application Version**
        What version of the application are you using?
  - type: input
    id: application-version
    attributes:
      label: Application Version
      description: The version of the application where the bug occurred.
      placeholder: e.g. 1.2.3
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other context about the problem here.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context about the problem.
      placeholder: 'More details...'
    validations:
      required: false
